name: Deploy Property API to Digitalocean
run-name: ${{ github.actor }} is deploying the application 🚀

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.1.14"
          extensions: curl, fileinfo, openssl, pdo_mysql, mbstring, intl, gd
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run composer install
        run: |
          composer install -q -n --no-ansi --no-scripts --no-progress --prefer-dist

      - name: Initialize env
        run: |
          echo APP_ENV=testing > .env
          echo APP_KEY= >> .env
          echo APP_URL="${{ secrets.APP_URL }}" >> .env
          echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
          echo DB_DATABASE="${{ secrets.DB_DATABASE }}" >> .env
          echo DB_USERNAME="${{ secrets.DB_USERNAME }}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
          echo CLOUDINARY_URL="${{ secrets.CLOUDINARY_URL }}" >> .env
          echo CLOUDINARY_UPLOAD_PRESET="${{ secrets.CLOUDINARY_UPLOAD_PRESET }}" >> .env
          echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
          echo ACCOUNT_API="${{ secrets.ACCOUNT_API }}" >> .env
          php artisan key:generate
          php artisan config:cache

      - name: Run tests
        run: php artisan test --without-tty

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: test
    if: always() && needs.test.result == 'success'
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd /var/www/property-api
            git pull origin main
            composer install -q -n --no-ansi --no-scripts --no-progress --prefer-dist
            echo APP_ENV=production > .env
            echo APP_KEY= >> .env
            echo APP_URL="${{ secrets.APP_URL }}" >> .env
            echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
            echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
            echo DB_DATABASE="${{ secrets.DB_DATABASE }}" >> .env
            echo DB_USERNAME="${{ secrets.DB_USERNAME }}" >> .env
            echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
            echo SSL_MODE=REQUIRED >> .env
            echo CLOUDINARY_URL="${{ secrets.CLOUDINARY_URL }}" >> .env
            echo CLOUDINARY_UPLOAD_PRESET="${{ secrets.CLOUDINARY_UPLOAD_PRESET }}" >> .env
            echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
            echo ACCOUNT_API="${{ secrets.ACCOUNT_API }}" >> .env
            php artisan migrate
            php artisan key:generate
            php artisan optimize
            sudo certbot renew
            sudo service nginx restart
            sudo systemctl reload nginx
