name: Test Account API on pull request
run-name: ${{ github.actor }} is testing the application ✅

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: "8.1.3"
          extensions: curl, fileinfo, openssl, pdo_mysql, mbstring, intl, gd
          ini-values: post_max_size=8M, max_execution_time=30
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run composer install
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Initialize env
        run: |
          echo APP_ENV=testing > .env
          echo APP_KEY= >> .env
          echo APP_URL="${{ secrets.APP_URL }}" >> .env
          echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
          echo DB_DATABASE="${{ secrets.DB_DATABASE }}" >> .env
          echo DB_USERNAME="${{ secrets.DB_USERNAME }}" >> .env
          echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
          echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
          echo ACCOUNT_API="${{ secrets.ACCOUNT_API }}" >> .env
          php artisan config:cache

      - name: Run tests
        run: php artisan test
